### ISSUE TITLE
Allow `sitemapPath` to omit `https://`.

### ISSUE THREAD

**Issue by ehmicky** [cdeleeuwe/netlify-plugin-submit-sitemap#10]
Some users are passing the following values to `sitemapPath`: `activepure-biz.netlify.app` and `www.activepure.biz `. This fails becomes it lacks the scheme (`https://`). 

Would it be a good idea to prepend a default scheme when the scheme is missing?

**Comment by cdeleeuwe** [comment]
@ehmicky thanks for your suggestion. Yes, sounds good. Will add it.

**Comment by cdeleeuwe** [comment]
Resolved in #11

**Comment by ehmicky** [comment]
Thanks! :tada:
