### ISSUE TITLE
Services are pinged for local builds as well

### ISSUE THREAD

**Issue by lunelson** [cdeleeuwe/netlify-plugin-submit-sitemap#15]
The `isProduction` check should also look for the `NETLIFY` env variable. In local builds, this is `undefined`. The full check should be `if (NETLIFY && CONTEXT == 'production')`

**Comment by cdeleeuwe** [comment]
Thanks a lot for finding this improvement @lunelson :). Agree, I think we could use the "IS_LOCAL" constant to check if it's run locally. https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#constants

Feel free to make a PR, else I can push an update in the next few days.

**Comment by lunelson** [comment]
Oh nice! I didn't know about the `IS_LOCAL` context variable, that sounds like it would make the most sense—but also combined with the `CONTEXT == 'production'` check no? For example `IS_LOCAL` will be false on branch and preview deploys...

**Comment by cdeleeuwe** [comment]
Resolved in https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/pull/16. Thanks @lunelson
