### ISSUE TITLE
Support for DuckDuckGo

### ISSUE THREAD

**Issue by blakegearin** [cdeleeuwe/netlify-plugin-submit-sitemap#19]
Hello, I'd use this if support for DuckDuckGo were to be added. To be clear, I don't know if DuckDuckGo has a similar process/system, so if they don't please let me know and close this out. Thanks.

**Comment by cdeleeuwe** [comment]
Hi @blakegearin , thanks for you suggestion. AFAIK DuckDuckGo doesn't have a way to submit/ping the sitemap.

**Comment by blakegearin** [comment]
According to [MonsterInsights](https://www.monsterinsights.com/submit-website-to-search-engines/):

> DuckDuckGo doesn’t offer any manual method where you can enter your sitemap or webpage URLs for indexing. It relies on search results from other search engines and then automatically indexes websites.

This lines up with articles on other similar websites. Perhaps you could explain this a little in your README in case others wonder about DDG

**Comment by cdeleeuwe** [comment]
@blakegearin Yes, sounds good! Feel free to make a PR if you want :). Else I will update it next week.
