### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ehmicky** [cdeleeuwe/netlify-plugin-submit-sitemap#3]
`curl` is not guaranteed to be available on a Windows machine.

Build plugins can be run locally with the Netlify CLI, so they can run on Windows.

The HTTP request could instead be performed using [`node-fetch`](https://github.com/node-fetch/node-fetch), [`got`](https://github.com/sindresorhus/got) or similar libraries. This would ensure it works on Windows.

What do you think?

**Comment by cdeleeuwe** [comment]
Fixed in https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/commit/4c3fb89eb062116829b600667c5d0b532754ab07
