### ISSUE TITLE
"Invalid date" error with Google Search Console

### ISSUE THREAD

**Issue by ebibibi** [cdeleeuwe/netlify-plugin-submit-sitemap#34]
When I put generated sitemap, google search console show sitemap contains error.
Error is "Invalid date".

![image](https://user-images.githubusercontent.com/322947/210209279-2e24b6a0-bd84-451a-9a0d-ae15fe7a06ef.png)

**Comment by cdeleeuwe** [comment]
@ebibibi sorry for the late response. This plugin is not actually generating the sitemap.. it only pings the search engines to tell them that there is a sitemap update. Will close this issue.
