### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by ehmicky** [cdeleeuwe/netlify-plugin-submit-sitemap#4]
Errors should be using either the `utils.build.failPlugin()` or `utils.build.failBuild()` method (documentation [here](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#error-reporting), instead of `console.log()` in: 

https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/blob/7d80db406c6ef7eabdd61e98a9a1fd6603eeddff/index.js#L37

And:

https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/blob/7d80db406c6ef7eabdd61e98a9a1fd6603eeddff/index.js#L26

This ensures that errors are correctly shown to users in the Netlify app.

**Comment by ehmicky** [comment]
This looks good, thanks!

Except for one thing:

https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/blob/078ea39f1e0f48621776221f2dcaca09b43bed23/index.js#L80

`failPlugin()` first argument should be the error message, not the success message.
And its second (optional) argument (`error`, not `errors`) should be a single `Error` instance.

**Comment by ehmicky** [comment]
This makes sense! This looks like your use case might be some sort of `utils.build.warn()` method. We actually have a [feature request for it](https://github.com/netlify/build/issues/1248). In the meantime, `console.log()` is probably best :+1: 

On the other hand, if all providers have failed, shouldn't the plugin fail (with `utils.build.failPlugin()` or `utils.build.failBuild()`)?

**Comment by cdeleeuwe** [comment]
@ehmicky Aah yes, something like ```utils.build.warn()``` is exactly what I am looking for :). I think for now I will ```console.log()``` the errors, and will use something like ```utils.build.failPlugin(`${ errors.length} sitemap submissions failed`)```. So at least the user sees something failed, but doesn't stop the build.

**Comment by ehmicky** [comment]
This looks good! One last thing: the `error` argument must be a single `Error` instance, not an array of `Error` instances. You can either wrap the errors in a single `Error`, or only pass the first one.
