### ISSUE TITLE
Show the result in the deploy summary

### ISSUE THREAD

**Issue by ehmicky** [cdeleeuwe/netlify-plugin-submit-sitemap#5]
The final result: 

https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/blob/7d80db406c6ef7eabdd61e98a9a1fd6603eeddff/index.js#L41

could be shown in the deploy summary by using `utils.status.show()` (documentation [here](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#logging)):

```js
utils.status.show({ summary: `Sitemap submitted successfully to ${provider}` })
```

**Comment by cdeleeuwe** [comment]
@ehmicky I changed it, but I cant see it in the deploy summary in Netlify's UI. When using ```netlify build``` locally I can see it in the logs like below
![image](https://user-images.githubusercontent.com/11793788/83763725-3a869500-a6a3-11ea-8797-3301b6a956bb.png)

This is an example of a successful build: https://app.netlify.com/sites/netlify-plugin-submit-sitemap/deploys/5ed8f744219cf900060c9ca2

Any idea why it doesn't show in the UI?

**Comment by ehmicky** [comment]
Thanks for double checking! We have implemented `utils.status.show()` in the terminal/local logs, but not in the UI yet (although this should be done very soon).

**Comment by cdeleeuwe** [comment]
Aah OK, got it :). Is it OK if for now, I use both ```console.log``` and ```utils.status.show()``` for the end result?
