### ISSUE TITLE
Add error handling for invalid `sitemapPath`

### ISSUE THREAD

**Issue by ehmicky** [cdeleeuwe/netlify-plugin-submit-sitemap#9]
When `sitemapPath` is not a valid URL, the following line throws:

https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/blob/6257766f57bc8d57a7317e1c36dffa44aa2aecc4/index.js#L58

A `try`/`cache`/`utils.build.failBuild()` block should be added to handle this and report it as a user error, instead of a plugin error.

**Comment by cdeleeuwe** [comment]
Resolved in #11
